pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
allow-branch = ["main"]
tag-message = "chore(release): release version {{version}}"
pre-release-commit-message = "chore(release): bump version {{version}}"